In [1]:
# Konditionszahl
import numpy as np

A = np.array([
	[1, 0, 2],
	[0, 1, 0],
	[1E-4, 0, 1E-4]
])

order = np.Infinity

A_norm = np.linalg.norm(A, order)

A_inv = np.linalg.inv(A)
A_inv_norm = np.linalg.norm(A_inv, order)


print ("Normal")
print (A)
print (f"Kond: {A_norm} \n")

print ("Inverse")
print (A_inv)
print (f"Kond: {A_inv_norm} \n")

print ("Norm")
print (A_norm * A_inv_norm)

Normal
[[1.e+00 0.e+00 2.e+00]
 [0.e+00 1.e+00 0.e+00]
 [1.e-04 0.e+00 1.e-04]]
Kond: 3.0 

Inverse
[[-1.e+00  0.e+00  2.e+04]
 [ 0.e+00  1.e+00  0.e+00]
 [ 1.e+00  0.e+00 -1.e+04]]
Kond: 20001.0 

Konditionszahl
60003.0


In [3]:
# Relativer Fehler
import numpy as np

A = np.array([
	[1,2],
	[3, 4]
])

# Fehlermatrix
As = A + np.random.rand(2, 2) / 1E5

rel_error = np.linalg.norm(A - As, order) / np.linalg.norm(A, order)

print ("Relativer Fehler", rel_error)

Relativer Fehler 2.071029295391824e-06


In [4]:
# Relativer Fehler in einem Bereich

import numpy as np

A = np.array([
	[1, 0, 2],
	[0, 1, 0],
	[1E-4, 0, 1E-4]
])

# Maximaler relativer Fehler 
max_rel_error = 0.01
order = np.Infinity

cond_a = np.linalg.cond(A)
print("Konditionszahl a", cond_a)
print ("Epsilon", max_rel_error / cond_a )

Konditionszahl a 50000.000179999995
Epsilon 1.9999999928000002e-07


In [5]:
# Tatsächlicher Fehler
import numpy as np

A = np.array([
	[1, 0, 2],
	[0, 1, 0],
	[1E-4, 0, 1E-4]
])

# Maximaler relativer Fehler 
max_rel_error = 0.01
order = np.Infinity

cond_a = np.linalg.cond(A)
epsilon = max_rel_error / cond_a

print ("{a} ≤ (1 - {e})".format(a=cond_a, e=epsilon))

print("Resultat: ", (1-epsilon)/cond_a)

50000.000179999995 ≤ (1 - 1.9999999928000002e-07)
Resultat:  1.9999995928000032e-05
